stages:
  - build
  - deploy

build_image:  
  stage: build
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS  
  script:
    - docker build -t "image_name" .
    - docker push "aws_ecr_repo_name"

deploy_app:
  stage: deploy 
  script: 
    - ssh -i $SSH_KEY ec2user@162.23.223.118
      docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&  
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -p 80:80 $IMAGE_NAME:$IMAGE_TAG 